"""Add TimerTriggerConfig and related link tables

Revision ID: 18ae93446498
Revises: 
Create Date: 2025-04-16 15:54:00.683789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ae93446498'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alma_api_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alma_api_permissions_permission_name'), 'alma_api_permissions', ['permission_name'], unique=True)
    op.create_table('institution_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iz_code', sa.String(length=50), nullable=False),
    sa.Column('iz_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_zones_iz_code'), 'institution_zones', ['iz_code'], unique=True)
    op.create_table('timer_trigger_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('email_subject', sa.String(length=500), nullable=False),
    sa.Column('dataprep_handler_type', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timer_trigger_configs_config_name'), 'timer_trigger_configs', ['config_name'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_name', sa.String(length=255), nullable=False),
    sa.Column('required_permission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['required_permission_id'], ['alma_api_permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_analysis_name'), 'analyses', ['analysis_name'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_zone_id', sa.Integer(), nullable=False),
    sa.Column('api_key_value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_zone_id'], ['institution_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('institution_zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_zone_id'], ['institution_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    op.create_table('api_key_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['alma_api_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'permission_id', name='uq_api_key_permission')
    )
    op.create_table('iz_analysis_connector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_zone_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('analysis_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['institution_zone_id'], ['institution_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_zone_id', 'analysis_id', name='uq_iz_analysis_connector'),
    sa.UniqueConstraint('institution_zone_id', 'analysis_path', name='uq_iz_analysis_path')
    )
    op.create_table('trigger_config_user_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_config_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trigger_config_id'], ['timer_trigger_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger_config_id', 'user_id', name='uq_trigger_user_link')
    )
    op.create_table('user_analysis_connector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'analysis_id', name='uq_user_analysis')
    )
    op.create_table('trigger_config_iz_analysis_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_config_id', sa.Integer(), nullable=False),
    sa.Column('iz_analysis_connector_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['iz_analysis_connector_id'], ['iz_analysis_connector.id'], ),
    sa.ForeignKeyConstraint(['trigger_config_id'], ['timer_trigger_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger_config_id', 'iz_analysis_connector_id', name='uq_trigger_iz_analysis_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trigger_config_iz_analysis_link')
    op.drop_table('user_analysis_connector')
    op.drop_table('trigger_config_user_link')
    op.drop_table('iz_analysis_connector')
    op.drop_table('api_key_permissions')
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_analyses_analysis_name'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_timer_trigger_configs_config_name'), table_name='timer_trigger_configs')
    op.drop_table('timer_trigger_configs')
    op.drop_index(op.f('ix_institution_zones_iz_code'), table_name='institution_zones')
    op.drop_table('institution_zones')
    op.drop_index(op.f('ix_alma_api_permissions_permission_name'), table_name='alma_api_permissions')
    op.drop_table('alma_api_permissions')
    # ### end Alembic commands ###
